default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  user: bergen
  password: bergen

development:
  <<: *default
  database: bergen_development

test:
  <<: *default
  database: bergen_test

production:
  <<: *default
  database: bergen_production
  username: bergen
  password: <%= ENV['BERGEN_DATABASE_PASSWORD'] %>
